-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOQgRQdE9JyVqliJi
oC3kEniOtza02szRsKakqLlG2nGgCgYIKoZIzj0DAQehRANCAASwTwvQiJP8ygxs
AdywXHbI/XgCmLKhwncvOEshfhE0ccVco3j+S07uFVN7aXPASDqBvfoX0W7z4AoF
Y5FT5C88
-----END PRIVATE KEY-----