# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ConditionController' do



    pod 'Moya', :git => 'https://github.com/Moya/Moya'
    pod 'Moya-ObjectMapper', :git => 'https://github.com/ivanbruel/Moya-ObjectMapper'
    pod 'SwiftyJSON'
    pod 'RealmSwift'
    pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD'
    
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0' # or '3.0'
            end
        end
    end
end






